# Site settings
title: Instantly renew car insurance
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Instantly renew your car insurance in 4 easy steps from leading companies like Bajaj-Allianz, HDFC-ERGO, 
  Iffco-Tokio, Bharti-AXA, Liberty-Videocon, New India Assurance Co.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.renewbuy.com" # the base hostname & protocol for your site
twitter_username: renewbuy
#github_username:  jekyll

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
